// Package domain contains core domain types and interfaces for the quant trading system.
// All types are market-agnostic and can be used across different markets.
package domain

import (
	"context"
	"time"
)

// Direction represents trading direction
type Direction string

const (
	DirectionLong  Direction = "long"
	DirectionShort Direction = "short"
	DirectionClose Direction = "close"
	DirectionHold  Direction = "hold"
)

// OHLCV represents daily candlestick data
type OHLCV struct {
	Symbol    string
	Date      time.Time
	Open      float64
	High      float64
	Low       float64
	Close     float64
	Volume    float64
	Turnover  float64
	TradeDays int
}

// Stock represents a tradable security
type Stock struct {
	Symbol        string
	Name          string
	Exchange      string
	Industry      string
	MarketCap     float64
	ListDate      time.Time
	Status        string // active, suspended, delisted
}

// Fundamental represents fundamental financial data
type Fundamental struct {
	Symbol         string
	Date          time.Time
	PE            float64
	PB            float64
	PS            float64
	ROE           float64
	ROA           float64
	DebtToEquity  float64
	GrossMargin   float64
	NetMargin     float64
	Revenue       float64
	NetProfit     float64
	TotalAssets   float64
	TotalLiab     float64
}

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Symbol          string
	Date            time.Time
	Direction       Direction
	Strength        float64       // 0.0 - 1.0, confidence level
	CompositeScore  float64       // overall factor score
	Factors         map[string]float64 // factor contributions
	Metadata        map[string]any
}

// Position represents a single position in the portfolio
type Position struct {
	Symbol        string
	Quantity      float64
	AvgCost       float64
	CurrentPrice  float64
	MarketValue   float64
	UnrealizedPnL float64
	RealizedPnL   float64
	Weight        float64
	EntryDate     time.Time
}

// Portfolio represents the current portfolio state
type Portfolio struct {
	Cash         float64
	Positions    map[string]Position
	TotalValue   float64
	DailyReturn  float64
	UpdatedAt    time.Time
}

// MarketRegime represents detected market regime
type MarketRegime struct {
	Trend      string    // "bull", "bear", "sideways"
	Volatility string    // "low", "medium", "high"
	Sentiment  float64   // -1.0 to 1.0
	Timestamp  time.Time
}

// RiskMetrics contains portfolio risk measurements
type RiskMetrics struct {
	Volatility       float64
	Beta             float64
	SharpeRatio      float64
	SortinoRatio     float64
	MaxDrawdown      float64
	MaxDrawdownDate  time.Time
	VaR95            float64 // Value at Risk (95%)
	CVaR95           float64 // Conditional VaR
}

// BacktestResult contains the result of a backtest run
type BacktestResult struct {
	StartDate        time.Time
	EndDate          time.Time
	TotalReturn      float64
	AnnualReturn     float64
	SharpeRatio      float64
	SortinoRatio     float64
	MaxDrawdown      float64
	MaxDrawdownDate  time.Time
	WinRate          float64
	TotalTrades      int
	WinTrades        int
	LoseTrades       int
	AvgHoldingDays   float64
	CalmarRatio      float64
	PortfolioValues  []PortfolioValue // time series of portfolio values
	Trades           []Trade
}

// PortfolioValue represents a single portfolio value snapshot
type PortfolioValue struct {
	Date        time.Time
	TotalValue  float64
	Cash        float64
	Positions   float64
}

// Trade represents a single trade execution
type Trade struct {
	ID          string
	Symbol      string
	Direction   Direction
	Quantity    float64
	Price       float64
	Commission  float64
	Timestamp   time.Time
}

// BacktestParams contains parameters for a backtest run
type BacktestParams struct {
	StrategyName   string
	StockPool      []string   // list of stock symbols
	StartDate      time.Time
	EndDate        time.Time
	InitialCapital float64
	RiskFreeRate   float64
}

// Strategy interface must be implemented by all trading strategies
type Strategy interface {
	Name() string
	Description() string
	Configure(config map[string]any) error
	Signals(ctx context.Context, stocks []Stock, ohlcv map[string][]OHLCV, fundamental map[string][]Fundamental, date time.Time) ([]Signal, error)
	Weight(signal Signal, portfolioValue float64) float64
	Cleanup()
}

// MarketDataProvider defines the interface for accessing market data
type MarketDataProvider interface {
	GetOHLCV(ctx context.Context, symbol string, start, end time.Time) ([]OHLCV, error)
	GetFundamental(ctx context.Context, symbol string, date time.Time) (*Fundamental, error)
	GetStocks(ctx context.Context, exchange string) ([]Stock, error)
	GetLatestPrice(ctx context.Context, symbol string) (float64, error)
	GetIndexConstituents(ctx context.Context, indexCode string) ([]string, error)
}

// RiskManager defines the interface for risk management
type RiskManager interface {
	CalculatePosition(ctx context.Context, signal Signal, portfolio *Portfolio, regime *MarketRegime) (PositionSize, error)
	DetectRegime(ctx context.Context, ohlcv []OHLCV) (*MarketRegime, error)
	CheckStopLoss(ctx context.Context, positions []Position, prices map[string]float64) ([]StopLossEvent, error)
}

// PositionSize contains the calculated position size
type PositionSize struct {
	Size       float64
	Weight     float64
	StopLoss   float64
	TakeProfit float64
	RiskScore  float64
}

// StopLossEvent represents a stop loss trigger event
type StopLossEvent struct {
	Symbol   string
	Type     string    // "stop_loss" or "take_profit"
	Price    float64
	Quantity float64
	Reason   string
}

// Config represents YAML config structure
type Config struct {
	Database DatabaseConfig
	Redis    RedisConfig
	Services map[string]ServiceConfig
	Tushare  TushareConfig
}

// DatabaseConfig holds database connection settings
type DatabaseConfig struct {
	Host     string
	Port     int
	User     string
	Password string
	Database string
	SSLMode  string
}

// RedisConfig holds Redis connection settings
type RedisConfig struct {
	URL string
}

// ServiceConfig holds generic service settings
type ServiceConfig struct {
	Host string
	Port int
}

// TushareConfig holds tushare API settings
type TushareConfig struct {
	Token    string
	BaseURL  string
	MaxRetries int
}
