// Package domain contains core domain types and interfaces for the
// quant trading system.
//
// S7-P3-4 (ODR-043 D3): Market-data types (OHLCV, Stock, Fundamental,
// etc.) now live in pkg/domain/market. This package re-exports them as
// type aliases for backward compatibility. New code SHOULD import
// pkg/domain/market directly.
package domain

import (
	"context"
	"time"

	"github.com/ruoxizhnya/quant-trading/pkg/domain/market"
)

// Direction represents trading direction
type Direction string

const (
	DirectionLong  Direction = "long"
	DirectionShort Direction = "short"
	DirectionClose Direction = "close"
	DirectionHold  Direction = "hold"
)

// OrderType represents the type of order.
//
// P1-3 (ODR-016) — LiveEngine 限价单支持:
//   - Market:  市价单, 立即按当前价成交
//   - Limit:   限价单, 仅在价格穿越限价时成交
//   - Stop:    止损/止损买入单, 价格触及 StopPrice 后转为市价单
//   - Trailing: 跟踪止损单, 跟踪市场价 HWM (High Water Mark) 后动态调整
type OrderType string

const (
	OrderTypeMarket   OrderType = "market"
	OrderTypeLimit    OrderType = "limit"
	OrderTypeStop     OrderType = "stop"
	OrderTypeTrailing OrderType = "trailing"
)

// S7-P3-4 (ODR-043 D3): Market-data types migrated to pkg/domain/market.
// These aliases preserve backward compatibility: domain.OHLCV and
// market.OHLCV are the SAME type (not two different types), so all
// existing consumer code compiles unchanged. New code SHOULD prefer
// the `market.` package path.
//
// To migrate a file: change `domain.OHLCV` → `market.OHLCV` and the
// import. No type conversion is needed.
type (
	OHLCV              = market.OHLCV
	Stock              = market.Stock
	IndexConstituent   = market.IndexConstituent
	Split              = market.Split
	Dividend           = market.Dividend
	Fundamental        = market.Fundamental
	FundamentalData    = market.FundamentalData
	MarketDataProvider = market.Provider // renamed; alias keeps old name
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Symbol         string             `json:"symbol"`
	Date           time.Time          `json:"date"`
	Direction      Direction          `json:"direction"`
	Strength       float64            `json:"strength"`
	CompositeScore float64            `json:"composite_score"`
	Factors        map[string]float64 `json:"factors"`
	Metadata       map[string]any     `json:"metadata"`
	LimitPrice     float64            `json:"limit_price"` // 0 for market orders
	OrderType      OrderType          `json:"order_type"`  // market or limit
}

// Position represents a single position in the portfolio
type Position struct {
	Symbol        string    `json:"symbol"`
	Quantity      float64   `json:"quantity"`
	AvgCost       float64   `json:"avg_cost"`
	CurrentPrice  float64   `json:"current_price"`
	MarketValue   float64   `json:"market_value"`
	UnrealizedPnL float64   `json:"unrealized_pnl"`
	RealizedPnL   float64   `json:"realized_pnl"`
	Weight        float64   `json:"weight"`
	EntryDate     time.Time `json:"entry_date"`
	// T+1 Settlement tracking (A-share rule: shares bought today cannot be sold today)
	BuyDate           time.Time `json:"buy_date"`           // Last buy date for this position
	QuantityToday     float64   `json:"quantity_today"`     // Shares bought today (not yet sellable)
	QuantityYesterday float64   `json:"quantity_yesterday"` // Shares from previous days (sellable today)
	// Metadata is an open extension slot used by risk / strategy
	// modules to persist per-position state. P2-14 take-profit rules
	// use it to track trailing-stop activation / high-water mark /
	// tiered-take-profit current level. Keys are namespaced strings
	// (e.g. "trailing_high", "tiered_current_level").
	Metadata map[string]any `json:"metadata,omitempty"`
}

// Portfolio represents the current portfolio state
type Portfolio struct {
	Cash        float64             `json:"cash"`
	Positions   map[string]Position `json:"positions"`
	TotalValue  float64             `json:"total_value"`
	DailyReturn float64             `json:"daily_return"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// MarketRegime represents detected market regime
type MarketRegime struct {
	Trend      string    `json:"trend"`      // "bull", "bear", "sideways"
	Volatility string    `json:"volatility"` // "low", "medium", "high"
	Sentiment  float64   `json:"sentiment"`  // -1.0 to 1.0
	Timestamp  time.Time `json:"timestamp"`
}

// RiskMetrics contains portfolio risk measurements
type RiskMetrics struct {
	Volatility      float64   `json:"volatility"`
	Beta            float64   `json:"beta"`
	SharpeRatio     float64   `json:"sharpe_ratio"`
	SortinoRatio    float64   `json:"sortino_ratio"`
	MaxDrawdown     float64   `json:"max_drawdown"`
	MaxDrawdownDate time.Time `json:"max_drawdown_date"`
	VaR95           float64   `json:"var_95"`  // Value at Risk (95%)
	CVaR95          float64   `json:"cvar_95"` // Conditional VaR
}

// Order represents a trading order.
//
// P1-3 (ODR-016) — LiveEngine 限价单: 扩展了 Stop/Trailing 字段.
//   - StopPrice:    触发价 (OrderType=Stop 或 Trailing)
//   - TrailAmount:  跟踪止损绝对偏移 (单位: 元, 与 TrailPercent 互斥, 二者择一)
//   - TrailPercent: 跟踪止损百分比偏移 (0.05 = 5%, 与 TrailAmount 互斥)
//   - HighWaterMark: 跟踪止损运行期 HWM (由 LiveEngine 内部维护, 调用方不应预设)
//
// 限价单 / 止损单 的撮合语义:
//   - Limit Buy:   Ask <= LimitPrice        时成交
//   - Limit Sell:  Bid >= LimitPrice        时成交
//   - Stop Buy:    Ask >= StopPrice         时按市价成交 (突破追涨)
//   - Stop Sell:   Bid <= StopPrice         时按市价成交 (破位止损)
//   - Trailing Buy:  HWM 上升且 (HWM - TrailOffset) 触发后转市价单
//   - Trailing Sell: HWM 上升且 (HWM - TrailOffset) 触发后转市价单 (回撤到位止损)
type Order struct {
	ID         string    `json:"id"`
	Symbol     string    `json:"symbol"`
	Direction  Direction `json:"direction"` // long or short
	OrderType  OrderType `json:"order_type"`
	Quantity   float64   `json:"quantity"`
	LimitPrice float64   `json:"limit_price"` // 0 for market orders
	// P1-3 扩展字段
	StopPrice     float64   `json:"stop_price,omitempty"`      // 触发价
	TrailAmount   float64   `json:"trail_amount,omitempty"`    // 跟踪绝对偏移
	TrailPercent  float64   `json:"trail_percent,omitempty"`   // 跟踪百分比偏移
	HighWaterMark float64   `json:"high_water_mark,omitempty"` // 跟踪止损 HWM (内部维护)
	Timestamp     time.Time `json:"timestamp"`
	FilledQty     float64   `json:"filled_qty"`
	FillPrice     float64   `json:"fill_price"`
	Status        string    `json:"status"` // "filled" / "partial" / "cancelled" / "expired"
	Notes         string    `json:"notes"`
}

// TargetPosition tracks the target vs actual position for execution gap management.
type TargetPosition struct {
	Symbol      string    `json:"symbol"`
	TargetQty   float64   `json:"target_qty"`  // desired quantity from strategy signal
	ActualQty   float64   `json:"actual_qty"`  // what was actually executed
	PendingQty  float64   `json:"pending_qty"` // quantity not yet filled
	LastUpdated time.Time `json:"last_updated"`
}

// MarketDataProvider is now a type alias for market.Provider — see the
// alias block above (S7-P3-4). The interface definition was moved to
// pkg/domain/market/provider.go and renamed to market.Provider.

// RiskManager defines the interface for risk management
type RiskManager interface {
	CalculatePosition(ctx context.Context, signal Signal, portfolio *Portfolio, regime *MarketRegime, currentPrice float64, ohlcv []OHLCV) (PositionSize, error)
	DetectRegime(ctx context.Context, ohlcv []OHLCV) (*MarketRegime, error)
	CheckStopLoss(ctx context.Context, positions []Position, prices map[string]float64) ([]StopLossEvent, error)
}

// PositionSize contains the calculated position size
type PositionSize struct {
	Size       float64 `json:"size"`
	Weight     float64 `json:"weight"`
	StopLoss   float64 `json:"stop_loss"`
	TakeProfit float64 `json:"take_profit"`
	RiskScore  float64 `json:"risk_score"`
}

// StopLossEvent represents a stop loss trigger event
type StopLossEvent struct {
	Symbol   string  `json:"symbol"`
	Type     string  `json:"type"` // "stop_loss" or "take_profit"
	Price    float64 `json:"price"`
	Quantity float64 `json:"quantity"`
	Reason   string  `json:"reason"`
}

// Config represents YAML config structure
type Config struct {
	Database DatabaseConfig           `json:"database"`
	Redis    RedisConfig              `json:"redis"`
	Services map[string]ServiceConfig `json:"services"`
	Tushare  TushareConfig            `json:"tushare"`
}

// DatabaseConfig holds database connection settings
type DatabaseConfig struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	User     string `json:"user"`
	Password string `json:"password"`
	Database string `json:"database"`
	SSLMode  string `json:"ssl_mode"`
}

// RedisConfig holds Redis connection settings
type RedisConfig struct {
	URL string `json:"url"`
}

// ServiceConfig holds generic service settings
type ServiceConfig struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// TushareConfig holds tushare API settings
type TushareConfig struct {
	Token      string `json:"token"`
	BaseURL    string `json:"base_url"`
	MaxRetries int    `json:"max_retries"`
}

// StrategyConfig represents a stored strategy configuration.
type StrategyConfig struct {
	ID           int64     `json:"id"`
	StrategyID   string    `json:"strategy_id"` // unique slug, e.g. "my-momentum-v1"
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	StrategyType string    `json:"strategy_type"` // "momentum", "value", "quality", "composite"
	Params       string    `json:"params"`        // JSON string of params schema
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
