// Package strategy provides strategy management and plugin architecture.
package strategy

import (
	"context"

	"github.com/ruoxizhnya/quant-trading/pkg/domain"
)

// Parameter defines a configurable parameter for a strategy.
type Parameter struct {
	Name        string `json:"name"`
	Type       string `json:"type"`        // "int", "float", "string", "bool"
	Default     any    `json:"default"`
	Description string `json:"description"`
	Min        float64 `json:"min"`
	Max        float64 `json:"max"`
}

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	Symbol      string             `json:"symbol"`
	Action      string             `json:"action"`   // "buy", "sell", "hold"
	Strength    float64            `json:"strength"` // 0.0-1.0, how strong the signal is
	Price       float64            `json:"price"`    // reference price at signal time
	Date        interface{}        `json:"date"`     // signal generation timestamp
	Direction   domain.Direction   `json:"direction"` // long, short, close, hold
	Factors     map[string]float64 `json:"factors"`  // factor contributions (e.g., {"momentum": 0.6, "value": 0.4})
	Metadata    map[string]interface{} `json:"metadata"` // extended metadata
}

// Strategy interface must be implemented by all trading strategies.
// This is the canonical interface definition (v2) - unified across VISION.md, SPEC.md, and code.
type Strategy interface {
	Name() string                                                                    // unique strategy name
	Description() string                                                             // human-readable description
	Parameters() []Parameter                                                         // configurable parameters
	Configure(params map[string]interface{}) error                                   // dynamic parameter configuration
	GenerateSignals(ctx context.Context, bars map[string][]domain.OHLCV, portfolio *domain.Portfolio) ([]Signal, error)
	Weight(signal Signal, portfolioValue float64) float64                            // position weight based on signal strength
	Cleanup()                                                                        // release resources (cache, connections, etc.)
}
