// Package strategy provides strategy management and plugin architecture.
package strategy

import (
	"context"

	"github.com/ruoxizhnya/quant-trading/pkg/domain"
)

// Parameter defines a configurable parameter for a strategy.
type Parameter struct {
	Name        string `json:"name"`
	Type       string `json:"type"`        // "int", "float", "string", "bool"
	Default     any    `json:"default"`
	Description string `json:"description"`
	Min        float64 `json:"min"`
	Max        float64 `json:"max"`
}

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	Symbol   string  `json:"symbol"`
	Action   string  `json:"action"`   // "buy", "sell", "hold"
	Strength float64 `json:"strength"` // 0.0-1.0, how strong the signal is
	Price    float64 `json:"price"`   // reference price at signal time
}

// Strategy interface must be implemented by all trading strategies.
type Strategy interface {
	Name() string                                    // unique strategy name
	Description() string                             // human-readable description
	Parameters() []Parameter                         // configurable parameters
	GenerateSignals(ctx context.Context, bars map[string][]domain.OHLCV, portfolio *domain.Portfolio) ([]Signal, error)
}
