// Package strategy provides strategy management and plugin architecture.
package strategy

import (
	"time"

	"github.com/ruoxizhnya/quant-trading/pkg/domain"
)

// Parameter defines a configurable parameter for a strategy.
type Parameter struct {
	Name        string  `json:"name"`
	Type        string  `json:"type"` // "int", "float", "string", "bool"
	Default     any     `json:"default"`
	Description string  `json:"description"`
	Min         float64 `json:"min"`
	Max         float64 `json:"max"`
}

// Signal represents a trading signal generated by a strategy.
type FactorZScoreReader func(factor domain.FactorType, date time.Time, symbol string) (float64, bool)

type FactorAware interface {
	SetFactorCache(reader FactorZScoreReader)
}

// FundamentalSeries 是一只股票的财务记录序列，**按可用日升序**。
//
// 每条记录的 Date 必须是「可用日」（= COALESCE(ann_date, trade_date)），
// 不是报告期截止日。对齐发生在可用日上，才有 PIT 语义 —— 详见
// storage.GetFundamentalsPIT。
type FundamentalSeries = []domain.Fundamental

// FundamentalAware 是可选能力接口（P2-12），范式同 FactorAware。
//
// GenerateSignals 的签名里没有基本面参数，改签名要动所有策略实现，所以
// 走「引擎识别得了就注入、识别不了就跳过」这条路。策略如果没拿到基本面
// 却在表达式里用了 pe/pb，会**明确报错**而不是拿到一串 0 —— 见
// pkg/strategy/expression 的 OHLCVDataProvider。
type FundamentalAware interface {
	SetFundamentals(records map[string]FundamentalSeries)
}

type Signal struct {
	Symbol     string                 `json:"symbol"`
	Action     string                 `json:"action"`
	Strength   float64                `json:"strength"`
	Price      float64                `json:"price"`
	Date       interface{}            `json:"date"`
	Direction  domain.Direction       `json:"direction"`
	Factors    map[string]float64     `json:"factors"`
	Metadata   map[string]interface{} `json:"metadata"`
	OrderType  domain.OrderType       `json:"order_type"`
	LimitPrice float64                `json:"limit_price"`
}

// Strategy is the canonical composite trading-strategy interface
// (P1-24, ADR-020 §4). The interface is decomposed into 4 single-
// responsibility sub-interfaces in `interfaces.go`:
//
//   - StrategyCore     — Name, Description
//   - Configurable     — Parameters, Configure
//   - SignalGenerator  — GenerateSignals, Weight
//   - ResourceManaged  — Cleanup
//
// This file keeps the type definitions (Parameter, Signal, etc.).
// The interface itself is declared in `interfaces.go` to keep the
// decomposition rationale in one place. See that file for the
// full ISP / backward-compat design notes.
